### ISSUE TITLE
Rename gatsby and master branches.

### ISSUE THREAD

**Issue by benslv** [CyberSocYork/cybersocyork.github.io#26]
Change `master` to `publish`
Change `gatsby` to `master`

Source code will be stored on `master`.
Features developed on separate branches and merged into `master`.
Code changes on `master` will be automatically built and pushed to `publish`.
Gatsby Pages site will use `publish` branch for built site.

**Comment by benslv** [comment]
Did I get that summary correct?

**Comment by Sciencentistguy** [comment]
Done. 
`master` is the primary branch, which is deployed to `publish` whenever it is updated.
All development should be done on other branches, which are then merged via a pull request.

I also deleted some stale branches that have already been merged.
