### ISSUE TITLE
Crowded background on mobile devices

### ISSUE THREAD

**Issue by Xychic** [CyberSocYork/cybersocyork.github.io#6]
When viewing the website on a mobile device, the animated background has the 'nodes' too close, making the text hard to read

**Comment by silverben10** [comment]
Might be worth just disabling the background animation on mobile devices to improve performance, too.

**Comment by silverben10** [comment]
Should be fixed in latest build. From now on, the background animation should only be visible on medium screens an upwards, helping with text visibility.
