### ISSUE TITLE
Write a readme.md

### ISSUE THREAD

**Issue by Sciencentistguy** [CyberSocYork/cybersocyork.github.io#7]
A readme.md explaining how to operate the site would be quite useful
i.e. how to build, how to post blog posts, what is where, which branches to use for what etc

**Comment by silverben10** [comment]
Done!

**Comment by Sciencentistguy** [comment]
Right a couple of comments/issues with the readme.md:

* Tt seems to be very windows focused; suggesting that people go to websites and download software from there.
* At the end it says to contact a committee member to get your post submitted. I think it'd be better if people submitted pull requests rather than just having us do it, so that the git log accurately reflects who did what.
